### ISSUE TITLE
Variable vectors in matrix_frac

### ISSUE THREAD

**Issue by jean997** [JuliaOpt/Convex.jl#86]
Hi,
I would like to do something like

n = 100;
y = randn(n, 1); 
b = Variable(n);
s = Variable(n);
S = diagm(s);
problem = minimize(matrix_frac(y-b, S))

which gives me an error
`matrix_frac` has no method matching matrix_frac(::AdditionAtom, ::DiagMatrixAtom)

I think the issue is that y-b is an AbstractExpression rather than a constant because
problem = minimize(matrix_frac(y, S))
is fine. 

The original problem works fine in cvx in matlab.
Any solutions or workarounds would be greatly appreciated!

**Comment by madeleineudell** [comment]
Thanks for catching that; you're right that the definition we were using for the matrix fractional atom was more constrained than it needed to be. I've just pushed a fix (223201f5eb060b9e5d0872acd9ef03f63fe115e4); your example should work now.

With one caveat: currently SCS has some wonky behavior for SDPs, but MOSEK should work. We expect to have the issues with SCS resolved within a week.

**Comment by jean997** [comment]
Thanks - I'm pretty new to Julia and am having trouble updating to the new version. I tried Pkg.checkout("Convex") which told me there was nothing to update. I also tried removing Convex and cloning it from the url with no luck. Can you tell me what I should do?
Thanks!
Jean

**Comment by jean997** [comment]
Hmm - actually it looks like I did manage to update to the latest version (at least based on looking at my matrix_frac.jl file) but I'm still getting the same error.

**Comment by madeleineudell** [comment]
There was one more method missing. I've fixed it now (and added a test to ensure it's fixed for good).

The most sure way to pull from master is just to do it directly into the directory where julia stores package files:
```
cd ~/.julia/v0.3/Convex
git pull
```
If you do `Pkg.update()` after this it will be clobbered --- which is probably the preferred behavior. We should be updating the registered version of Convex as soon as we fix the problems with the other SDP solver.

**Comment by jean997** [comment]
Thanks so much! I've got it working.
