### ISSUE TITLE
julia v 0.3.10. Running example from Readme results in segfault

### ISSUE THREAD

**Issue by pilotrex** [JuliaOpt/Convex.jl#88]
Environment: Macbook Pro running Yosemite
Solver: SCS

I attach the output of the julia repl.

------------
```
julia> m = 4;  n = 5
5

julia> A = randn(m, n); b = randn(m, 1)
4x1 Array{Float64,2}:
 -0.110685
 -1.14888
  0.416149
  0.446634

julia> x = Variable(n)
Variable of
size: (5, 1)
sign: NoSign()
vexity: AffineVexity()

julia> problem = minimize(sum_squares(A * x + b), [x >= 0])
Problem:
minimize AbstractExpr with
head: qol_elem
size: (1, 1)
sign: Positive()
vexity: ConvexVexity()

subject to
Constraint:
>= constraint
lhs: Variable of
size: (5, 1)
sign: NoSign()
vexity: AffineVexity()
rhs: 0
vexity: AffineVexity()
current status: not yet solved

julia> solve!(problem)
ERROR: A->p (column pointers) decreasing
invalid linear system input data
ERROR: Validation returned failure
ERROR: NULL input

signal (11): Segmentation fault: 11
_platform_memmove$VARIANT$Unknown at /usr/lib/system/libsystem_platform.dylib (unknown line)
Segmentation fault: 11
```

**Comment by mlubin** [comment]
@pilotrex, when did you install Convex.jl? Try running:
```
using Homebrew
Homebrew.update()
```
This should be fixed by https://github.com/staticfloat/homebrew-juliadeps/pull/55.

**Comment by pilotrex** [comment]
Thanks! tried it:
HEAD is now at 0018501 outdated: output full name
HEAD is now at 5b3b59a Merge pull request #55 from staticfloat/staging

However I'm still getting a segfault. I installed the package yesterday as I'm just getting started with Julia

**Comment by madeleineudell** [comment]
I think we may need to tag the new version of SCS.jl in METADATA before
normal installs of Convex.jl work again?

On Fri, Jun 26, 2015 at 10:38 AM, Raul Cajias <notifications@github.com>
wrote:

> Thanks! tried it:
> HEAD is now at 0018501 outdated: output full name
> HEAD is now at 5b3b59a Merge pull request #55
> <https://github.com/JuliaOpt/Convex.jl/pull/55> from staticfloat/staging
>
> However I'm still getting a segfault. I installed the package yesterday as
> I'm just getting started with Julia
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaOpt/Convex.jl/issues/88#issuecomment-115710887>.
>



-- 
Madeleine Udell
www.stanford.edu/~udell

**Comment by mlubin** [comment]
@pilotrex, try running ``Pkg.update()``, restart Julia, and give the code another try.

**Comment by pilotrex** [comment]
@mlubin, @madeleineudell 
Works now! Thanks guys :)
